### ISSUE TITLE
Flashing issues on uwb board

### ISSUE THREAD

**Issue by antoinealb** [cvra/can-bootloader#81]
The UWB board has some issues with flashing. It might be due to the microcontroller having larger pages, causing timeouts.

Example output:

```
Flashing firmware (size: 232244 bytes)
Erasing pages...
Traceback (most recent call last):
  File "/usr/local/bin/bootloader_flash", line 11, in <module>
    load_entry_point('cvra-bootloader==2.1.0', 'console_scripts', 'bootloader_flash')()
  File "/usr/local/lib/python3.6/site-packages/cvra_bootloader/bootloader_flash.py", line 200, in main
    args.ids, page_size=args.page_size)
  File "/usr/local/lib/python3.6/site-packages/cvra_bootloader/bootloader_flash.py", line 75, in flash_binary
    pbar.update(offset)
  File "/usr/local/lib/python3.6/site-packages/progressbar/bar.py", line 579, in update
    StdRedirectMixin.update(self, value=value)
  File "/usr/local/lib/python3.6/site-packages/progressbar/bar.py", line 141, in update
    DefaultFdMixin.update(self, value=value)
  File "/usr/local/lib/python3.6/site-packages/progressbar/bar.py", line 68, in update
    line = converters.to_unicode('\r' + self._format_line())
  File "/usr/local/lib/python3.6/site-packages/progressbar/bar.py", line 508, in _format_line
    widgets = ''.join(self._to_unicode(self._format_widgets()))
  File "/usr/local/lib/python3.6/site-packages/progressbar/bar.py", line 483, in _format_widgets
    widget_output = converters.to_unicode(widget(self, data))
  File "/usr/local/lib/python3.6/site-packages/progressbar/widgets.py", line 405, in __call__
    return ETA.__call__(self, progress, data, value=value, elapsed=elapsed)
  File "/usr/local/lib/python3.6/site-packages/progressbar/widgets.py", line 339, in __call__
    progress, data, value=value, elapsed=elapsed)
  File "/usr/local/lib/python3.6/site-packages/progressbar/widgets.py", line 321, in _calculate_eta
    eta_seconds = remaining * per_item
OverflowError: days=1209096132; must have magnitude <= 999999999
100% (232244 of 232244) |#######################################################| Elapsed Time: 0:00:00 Time: 0:00:00
```

**Comment by SyrianSpock** [comment]
Might be related to #65
